
[global]
kerberos method = secrets and keytab
template homedir = /home/%U@%D
workgroup = AA
password server = ns3.aa.lan
template shell = /bin/bash
security = ads
realm = AA.LAN
idmap config AA : range = 2000000-2999999
idmap config AA : backend = rid
idmap config * : range = 10000-999999
idmap config * : backend = tdb
winbind use default domain = no
winbind refresh tickets = yes
winbind offline logon = yes
winbind enum groups = no
winbind enum users = no

[share01]
	path = /samba/share01/
	read only = no
	acl_xattr:ignore system acls = yes